-- Exported from the connected D2D Supabase project on 2026-09-26.
create schema if not exists app;

create or replace function app.has_program_role(p_program_id uuid, p_roles text[]) returns boolean language sql stable security definer set search_path to 'public','app' as $$ select exists (select 1 from public.program_memberships pm where pm.program_id=p_program_id and pm.user_id=auth.uid() and pm.status='active' and pm.role=any(p_roles)); $$;
create or replace function app.is_enrolled_scholar(p_program_id uuid) returns boolean language sql stable security definer set search_path to 'public','app' as $$ select exists (select 1 from public.enrollments e join public.scholars s on s.id=e.scholar_id where e.program_id=p_program_id and s.auth_user_id=auth.uid() and e.status in ('active','completed')); $$;
create or replace function app.is_own_scholar(p_scholar_id uuid) returns boolean language sql stable security definer set search_path to 'public','app' as $$ select exists (select 1 from public.scholars s where s.id=p_scholar_id and s.auth_user_id=auth.uid() and s.status='active'); $$;
create or replace function app.is_program_member(p_program_id uuid) returns boolean language sql stable security definer set search_path to 'public','app' as $$ select app.has_program_role(p_program_id,array['admin','instructor','researcher','viewer']::text[]); $$;
create or replace function app.touch_updated_at() returns trigger language plpgsql set search_path to 'public','app' as $$ begin new.updated_at=now(); return new; end; $$;
create or replace function app.log_sensitive_write() returns trigger language plpgsql security definer set search_path to 'public','app' as $$ declare affected_id uuid; affected_program_id uuid; begin if tg_op='DELETE' then affected_id:=old.id; affected_program_id:=old.program_id; else affected_id:=new.id; affected_program_id:=new.program_id; end if; insert into public.audit_events(program_id,actor_user_id,action,resource_type,resource_id,metadata) values(affected_program_id,auth.uid(),lower(tg_op),tg_table_name,affected_id,jsonb_build_object('triggered_at',now())); return coalesce(new,old); end; $$;
create or replace function app.redeem_access_code(p_code_hash text, p_auth_user_id uuid) returns table(program_id uuid, cohort_id uuid, scholar_id uuid, pseudonym text) language plpgsql security definer set search_path to 'public','app' as $$ declare v_code public.scholar_access_codes%rowtype; v_scholar public.scholars%rowtype; begin if p_code_hash is null or length(p_code_hash)<>64 or p_auth_user_id is null then raise exception 'invalid_redemption_request' using errcode='22023'; end if; select * into v_code from public.scholar_access_codes where code_hash=p_code_hash and revoked_at is null and (expires_at is null or expires_at>now()) and redemption_count<max_redemptions order by created_at desc limit 1 for update; if not found then raise exception 'invalid_or_expired_code' using errcode='P0002'; end if; select * into v_scholar from public.scholars where id=v_code.scholar_id for update; if not found then raise exception 'scholar_not_found' using errcode='P0002'; end if; if v_scholar.auth_user_id is not null and v_scholar.auth_user_id<>p_auth_user_id then raise exception 'code_already_bound' using errcode='42501'; end if; update public.scholar_access_codes set redemption_count=redemption_count+1 where id=v_code.id; update public.scholars set auth_user_id=p_auth_user_id,updated_at=now() where id=v_scholar.id; return query select v_code.program_id,v_code.cohort_id,v_scholar.id,v_scholar.pseudonym; end; $$;
